apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutating-webhook-deployment
  labels:
    app: mutating-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutating-webhook
  template:
    metadata:
      labels:
        app: mutating-webhook
    spec:
      containers:
        - name: mutating-webhook
          image: acronhosbx.azurecr.io/mutating-webhook:v1.1
          imagePullPolicy: Always
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: mutating-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: mutating-webhook-svc
  labels:
    app: mutating-webhook
spec:
  ports:
    - port: 443
      targetPort: 8443
      name: https
  selector:
    app: mutating-webhook
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-cfg
  labels:
    app: mutating-webhook
webhooks:
  - name: mutating-webhook.interview.absa.co.za
    clientConfig:
      service:
        name: mutating-webhook-svc
        namespace: default
        path: "/mutate"
      #
      # run this to get base64 encoded certificate
      # kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}'
      #
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV5RENDQXJDZ0F3SUJBZ0lSQUo0c3lVdWFGL3NRcVBKcXQwN1VpSEV3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTVRreE1USXdNVFUwTWpRd1doY05ORGt4TVRFeU1UVTFNalF3V2pBTgpNUXN3Q1FZRFZRUURFd0pqWVRDQ0FpSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnSVBBRENDQWdvQ2dnSUJBTURyClA5SCtOMUVqZENqLzNwVUhNNXBQelNUUmxycmgvMU1CL2t4N05tbjFVUm5JZC9WcUttZzJYVlhEempobWV0b3YKQ1MrenQybTl1WDZ1L3NObnZ6cXZkcjRveWJJenFWb2VSUDF2NEV0S1F5OVhJT2Y5U0lCcVZabzlYZHJnaFhVVApYTi8vR0c5Q3ZyTzBMeTk2ZDQxbVBQYW85ODRReFFPdThjSkFzUHVFc2Nxd3E1d1hlc1VFcGRMYVVrbTVGMGdtCkMwMDdSeERyaHVWaElpcHRKYS90TE5zVjgyL1ZnVlpZYUdSQlcyVGwxVHpmSHJ1ZzB3dUxoQVRRbTRGbUJKVHUKNXZqb0d1ZVYraXNxUE5WQTF5blRiKzc2VkxEeVJ1QkhrQWRQRUFqZldUOFIxVDl4RTdKdGJHM0pXaTJqNzZacQphUVR3bWlOQ0RTdkU2c0F2OWMrM3RDVjFXdzJDV0NSMU5XTm1od3RackRvZTBHZkY1T0lxd3dpYjBzVjl0TjZSCko1UWl5T1NQOHBXbmNUWGhUZ1gvUWNKaXlua1p2S05QMERTa1JMS2VkbnFXYjltUTVFUEVyMjBNR29LNys4QkQKWUIxa09VZXZJZk5SMnMrTDQxbFNLV0lVcGpudTRQT21kTHJZLzZCYnUrRFI4RGZvaUp1YXpwTjYwOHFtN3dDVwpudGUwSzhBYnNiMllWcCtmQnhIdU02a0o5YmNyMlJXNXNyT3VEenB1LytUYkZBdmJxdkw4VVdqb1pnWTFIb3I4Ckw1S0VnL3RBeERaMnZLUnEvQVl5MzJoSGVuMEdFOVlrckxZOFFtSXc2UzkxdmxUOHpOV2Y0L2Yycm5raVBrR3QKNitkWStuRlNoOXhCY1ZNRmR5NzJSV1VCb1ZKck9ldVFncjRtMzhEOUFnTUJBQUdqSXpBaE1BNEdBMVVkRHdFQgovd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQWRQOThhCmRVUEs3dmxFUTlYWlpsOU1EMlZ1c1J1aSs5bkEra1g3Uyt6SS9BM3NVQ2NxZUR4R1lOcnBGL1N2c0o2aml2RUwKeWZDU1hwb3FGcTNZaUl0R3hEWVNYL3VJYnhiVnhEMUtMRDJsSFBCRG14LzB2MEp2M3VFQzJNTzRPUm1HRFpZaAorSGFTMDU4cURLSklmRWMwWW9SMWhmS2gvZHBJZm1PUU5jck1MZ0FBUVFpZGpmbFJDN3lFWmJHbVBmOEFsWGw5Cm0wVFBFM2pMQjlLOG4rUWU1RmlOVzR3azh4RFo0UDVmUjcvSVBEbnM0NFE1cTU4RmJLVGl6WDlrVGJ6UzN6bHMKWlJENFVhSHlOelZSSkNXeW13LytxR3lrYWpqWXJXRFA3bTU2Tk81ZU9TdFg1dzg4MzdyQ3A4elovMHhCNXJueApSbmo5Vm5Ld0NVM1dCdlM2dHA4aTkwRU1vTEFZWFNtei9MaXllbzNNaFZEQlErcUIyUGMwbjByaU1NYUQvYmFzCkxOQVVKRGRWam1WbCtaWW81VEdzMGxZKzRUa0E5VzMzU1dPYTRIY3daQVRFM2ZVeFNac1VVNmhreVdzQzNjWlIKWEFpaUg0MHFyZjFVam5TQkh4b2hVd212VGlhUFNzZEpjTmd4bkxrL1p6UE5sRG9ySGRtM3ozOGJMTDRIMXJFMQpDdzVqUGVjQkdvTnlNR3FPZm9FOStycGIzSkRyQ0FJaWc0R3lkcUN1UWRHeWNWaHZEMnY3UjBlMjFDek1hQ2QvClVNWGNJRXdEUW9BYUVXYzVMY25ieVhkb1EwTWdkZklTSkQ5TTZjWStXVkRuWU5QbEppK2lnbEYvNFNvVlZ3b0sKMk03ckcxWkJZRkNpYlRraGRLZFArbUJQWTFpcXJJOTRzM05KdVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","services","pods"]
    namespaceSelector:
      matchLabels:
        mutateme: enabled