---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mutating-webhook-configmap
data:
  config.labels: "eyJjb3N0LWNlbnRlciI6IjYwMDAxIiwiZW52aXJvbm1lbnQiOiJkZXYiLCJwcm9kdWN0IjoiY2FzaC1zZXJ2aWNlcyIsImNyZWF0b3IiOiJnYTJrdWFsIiwgIm93bmVyIjoiZ2Eya3VhbCJ9Cg=="
#  config.labels: "e30K" #empty label
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutating-webhook-deployment
  labels:
    app: mutating-webhook
  annotations:
    buildVersion: ${buildVersion}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutating-webhook
  template:
    metadata:
      labels:
        app: mutating-webhook
    spec:
      #pod must be running
      restartPolicy: Always
      containers:
        - name: mutating-webhook
          image: acronhosbx.azurecr.io/mutating-webhook:${tag}
          #imagePullPolicy: Always: the image is pulled every time the pod is started.
          imagePullPolicy: Always
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          env:
            -  name: LABEL_MAP
               valueFrom:
                 configMapKeyRef:
                   name: mutating-webhook-configmap
                   key: config.labels
      volumes:
        - name: webhook-certs
          secret:
            secretName: mutating-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: mutating-webhook-svc
  labels:
    app: mutating-webhook
spec:
  ports:
    - port: 443
      targetPort: 8443
      name: https
  selector:
    app: mutating-webhook
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-cfg
  labels:
    app: mutating-webhook
webhooks:
  - name: mutating-webhook.interview.absa.co.za
    clientConfig:
      service:
        name: mutating-webhook-svc
        namespace: default
        path: "/mutate"
      caBundle: ${caBundle}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","pods"]
    namespaceSelector:
      matchLabels:
        mutateme: enabled